import { arr, num, str, bool, any, undef , iterator } from './type.js'

const arrayList = [
  {
    name: 'Array.from()',
    mdnLink: 'https://developer.mozilla.org/zh-TW/docs/Web/JavaScript/Reference/Global_Objects/Array/from',
    explanation: '從類陣列（array-like）或是可迭代（iterable）物件建立一個新的 Array 實體。',
    returnType: arr,
    isChangeValue: false,
    parameter: 'arrayLike, *mapFn, *thisArg',
  },
  {
    name: 'Array.isArray()',
    mdnLink: 'https://developer.mozilla.org/zh-TW/docs/Web/JavaScript/Reference/Global_Objects/Array/isArray',
    explanation: '函式會檢查傳入的值是否為一個 Array。',
    returnType: bool,
    isChangeValue: false,
    parameter: 'obj',
  },
  {
    name: 'Array.of()',
    mdnLink: 'https://developer.mozilla.org/zh-TW/docs/Web/JavaScript/Reference/Global_Objects/Array/of',
    explanation: '由引數（arguments）的數量來建立一個新的 Array 實體，而不管引數的數量或類型為何。',
    returnType: arr,
    isChangeValue: false,
    parameter: 'el1, el2, ...elN',
  },
  {
    name: 'Array.prototype.concat()',
    mdnLink: 'https://developer.mozilla.org/zh-TW/docs/Web/JavaScript/Reference/Global_Objects/Array/concat',
    explanation: '用來合併兩個或多個陣列。此方法不會改變現有的陣列，回傳一個包含呼叫者陣列本身的值，作為代替的是回傳一個新陣列。',
    returnType: arr,
    isChangeValue: false,
    parameter: 'val1, val2, ...valN',
  },
  {
    name: 'Array.prototype.copyWithin()',
    mdnLink: 'https://developer.mozilla.org/zh-TW/docs/Web/JavaScript/Reference/Global_Objects/Array/copyWithin',
    explanation: '對陣列的一部分進行淺拷貝至同一陣列的另一位置並回傳此陣列，而不修改其大小。',
    returnType: arr,
    isChangeValue: true,
    parameter: 'target, *start, *end',
  },
  {
    name:'Array.prototype.entries()',
    mdnLink:'https://developer.mozilla.org/zh-TW/docs/Web/JavaScript/Reference/Global_Objects/Array/entries',
    explanation:'回傳一個包含陣列中每一個索引之鍵值對（key/value pairs）的新陣列迭代器（Array Iterator）物件。',
    returnType:iterator,
    isChangeValue:false,
    parameter:'',
  },
  {
    name:'Array.prototype.every()',
    mdnLink:'https://developer.mozilla.org/zh-TW/docs/Web/JavaScript/Reference/Global_Objects/Array/every',
    explanation:'測試陣列中的所有元素是否都通過了由給定之函式所實作的測試。',
    returnType:bool,
    isChangeValue:false,
    parameter:'callback(currentValue, *index, *array), *thisArg',
  },
  {
    name:'Array.prototype.fill()',
    mdnLink:'https://developer.mozilla.org/zh-TW/docs/Web/JavaScript/Reference/Global_Objects/Array/fill',
    explanation:'將陣列中索引的第一個到最後一個的每個位置全部填入一個靜態的值。',
    returnType:arr,
    isChangeValue:true,
    parameter:'val, *start, *end',
  },
  {
    name:'Array.prototype.filter()',
    mdnLink:'https://developer.mozilla.org/zh-TW/docs/Web/JavaScript/Reference/Global_Objects/Array/filter',
    explanation:'建立一個經指定之函式運算後，由原陣列中通過該函式檢驗之元素所構成的新陣列。',
    returnType:arr,
    isChangeValue:false,
    parameter:'callback(el, *index, *array), *thisArg',
  },
  {
    name:'Array.prototype.find()',
    mdnLink:'https://developer.mozilla.org/zh-TW/docs/Web/JavaScript/Reference/Global_Objects/Array/find',
    explanation:'回傳第一個滿足所提供之測試函式的元素值。否則回傳 undefined。',
    returnType:any,
    isChangeValue:false,
    parameter:'callback(el, *index, *array), *thisArg',
  },
  {
    name:'Array.prototype.findIndex()',
    mdnLink:'https://developer.mozilla.org/zh-TW/docs/Web/JavaScript/Reference/Global_Objects/Array/findIndex',
    explanation:'依據提供的測試函式，尋找陣列中符合的元素，並返回其 index（索引）。如果沒有符合的對象，將返回 -1 。',
    returnType:num,
    isChangeValue:false,
    parameter:'callback(el, *index, *array), *thisArg',
  },
  {
    name:'Array.prototype.forEach()',
    mdnLink:'https://developer.mozilla.org/zh-TW/docs/Web/JavaScript/Reference/Global_Objects/Array/forEach',
    explanation:'將陣列內的每個元素，皆傳入並執行給定的函式一次。',
    returnType:undef,
    isChangeValue:false,
    parameter:'callback(el, *index, *array), *thisArg',
  },
  {
    name:'Array.prototype.includes()',
    mdnLink:'https://developer.mozilla.org/zh-TW/docs/Web/JavaScript/Reference/Global_Objects/Array/includes',
    explanation:'判斷陣列是否包含特定的元素，並以此來回傳 true 或 false。',
    returnType:bool,
    isChangeValue:false,
    parameter:'searchEl, *fromIndex',
  },
  {
    name:'Array.prototype.indexOf()',
    mdnLink:'https://developer.mozilla.org/zh-TW/docs/Web/JavaScript/Reference/Global_Objects/Array/indexOf',
    explanation:'回傳給定元素於陣列中第一個被找到之索引，若不存在於陣列中則回傳 -1。',
    returnType:num,
    isChangeValue:false,
    parameter:'searchEl, *fromIndex',
  },
  {
    name:'Array.prototype.join()',
    mdnLink:'https://developer.mozilla.org/zh-TW/docs/Web/JavaScript/Reference/Global_Objects/Array/join',
    explanation:'將陣列（或一個類陣列（array-like）物件）中所有的元素連接、合併成一個字串，並回傳此字串。',
    returnType:str,
    isChangeValue:false,
    parameter:'*separator',
  },
  {
    name:'Array.prototype.keys()',
    mdnLink:'https://developer.mozilla.org/zh-TW/docs/Web/JavaScript/Reference/Global_Objects/Array/keys',
    explanation:'回傳一個包含陣列中的每一個索引之鍵（keys）的新 Array Iterator 物件。',
    returnType:iterator,
    isChangeValue:false,
    parameter:'',
  },
  {
    name:'Array.prototype.lastIndexOf()',
    mdnLink:'https://developer.mozilla.org/zh-TW/docs/Web/JavaScript/Reference/Global_Objects/Array/lastIndexOf',
    explanation:'回傳給定元素於陣列中最後一個被找到之索引，若不存在於陣列中則回傳 -1。搜尋的方向為由陣列尾部向後（即向前）尋找，啟始於 fromIndex。',
    returnType:num,
    isChangeValue:false,
    parameter:'searchEl, *fromIndex',
  },
  {
    name:'Array.prototype.map()',
    mdnLink:'https://developer.mozilla.org/zh-TW/docs/Web/JavaScript/Reference/Global_Objects/Array/map',
    explanation:'建立一個新的陣列，其內容為原陣列的每一個元素經由回呼函式運算後所回傳的結果之集合。',
    returnType:arr,
    isChangeValue:false,
    parameter:'callback(currentValue, *index, *array), *thisArg',
  },
  {
    name:'Array.prototype.pop()',
    mdnLink:'https://developer.mozilla.org/zh-TW/docs/Web/JavaScript/Reference/Global_Objects/Array/pop',
    explanation:'移除並回傳陣列的最後一個元素。此方法會改變陣列的長度。',
    returnType:any,
    isChangeValue:true,
    parameter:'',
  },
  {
    name:'Array.prototype.push()',
    mdnLink:'https://developer.mozilla.org/zh-TW/docs/Web/JavaScript/Reference/Global_Objects/Array/push',
    explanation:'添加一個或多個元素至陣列的末端，並且回傳陣列的新長度。',
    returnType:num,
    isChangeValue:true,
    parameter:'el1, el2, ...elN',
  },
  {
    name:'Array.prototype.reduce()',
    mdnLink:'https://developer.mozilla.org/zh-TW/docs/Web/JavaScript/Reference/Global_Objects/Array/reduce',
    explanation:'將一個累加器及陣列中每項元素（由左至右）傳入回呼函式，將陣列化為單一值。',
    returnType:any,
    isChangeValue:false,
    parameter:'callback(accumulator, currentValue, *currentIndex, *array), *initialValue'
  },
  {
    name:'Array.prototype.reduceRight()',
    mdnLink:'https://developer.mozilla.org/zh-TW/docs/Web/JavaScript/Reference/Global_Objects/Array/reduceRight',
    explanation:'將一個累加器及陣列中每項元素（由右至左）傳入回呼函式，將陣列化為單一值。',
    returnType:any,
    isChangeValue:false,
    parameter:'callback(accumulator, currentValue, *currentIndex, *array), *initialValue'
  },
  {
    name:'Array.prototype.reverse()',
    mdnLink:'https://developer.mozilla.org/zh-TW/docs/Web/JavaScript/Reference/Global_Objects/Array/reverse',
    explanation:'原地（in place）反轉（reverses）一個陣列。陣列中的第一個元素變為最後一個，而最後一個元素則變成第一個。',
    returnType:arr,
    isChangeValue:true,
    parameter:''
  },
  {
    name:'Array.prototype.shift()',
    mdnLink:'https://developer.mozilla.org/zh-TW/docs/Web/JavaScript/Reference/Global_Objects/Array/shift',
    explanation:'移除並回傳陣列的第一個元素。此方法會改變陣列的長度。',
    returnType:any,
    isChangeValue:true,
    parameter:''
  },
  {
    name:'Array.prototype.slice()',
    mdnLink:'https://developer.mozilla.org/zh-TW/docs/Web/JavaScript/Reference/Global_Objects/Array/slice',
    explanation:'回傳一個新陣列物件，為原陣列選擇之 begin 至 end（不含 end）部分的淺拷貝（shallow copy）。而原本的陣列將不會被修改。',
    returnType:arr,
    isChangeValue:false,
    parameter:'*begin, *end'
  },
  {
    name:'Array.prototype.some()',
    mdnLink:'https://developer.mozilla.org/zh-TW/docs/Web/JavaScript/Reference/Global_Objects/Array/some',
    explanation:'透過給定函式、測試陣列中是否至少有一個元素，通過該函式所實作的測試。這方法回傳的是布林值。',
    returnType:bool,
    isChangeValue:false,
    parameter:'callback(currentValue, *index, *array), *thisArg'
  },
  {
    name:'Array.prototype.sort()',
    mdnLink:'https://developer.mozilla.org/zh-TW/docs/Web/JavaScript/Reference/Global_Objects/Array/sort',
    explanation:'原地（in place）對一個陣列的所有元素進行排序，並回傳此陣列。排序不一定是穩定的（stable）。預設的排序順序是根據字串的 Unicode 編碼位置（code points）而定。',
    returnType:arr,
    isChangeValue:true,
    parameter:'*compareFunction'
  },

  {
    name:'Array.prototype.splice()',
    mdnLink:'https://developer.mozilla.org/zh-TW/docs/Web/JavaScript/Reference/Global_Objects/Array/splice',
    explanation:'藉由刪除既有元素並／或加入新元素來改變一個陣列的內容。',
    returnType:arr,
    isChangeValue:true,
    parameter:'start, *deleteCount, *item1, *item2, ...*itemN'
  },
  {
    name:'Array.prototype.toString()',
    mdnLink:'https://developer.mozilla.org/zh-TW/docs/Web/JavaScript/Reference/Global_Objects/Array/toString',
    explanation:'回傳一組字串，表示指定的陣列及其元素。',
    returnType:str,
    isChangeValue:false,
    parameter:''
  },
  {
    name:'Array.prototype.unShift()',
    mdnLink:'https://developer.mozilla.org/zh-TW/docs/Web/JavaScript/Reference/Global_Objects/Array/unShift',
    explanation:'添加一個或多個元素至陣列的開頭，並且回傳陣列的新長度。',
    returnType:num,
    isChangeValue:true,
    parameter:'el1, el2, ...elN'
  },
  {
    name:'Array.prototype.values()',
    mdnLink:'https://developer.mozilla.org/zh-TW/docs/Web/JavaScript/Reference/Global_Objects/Array/values',
    explanation:'回傳一個包含陣列中的每一個索引之對應值（values）的新 Array Iterator 物件。',
    returnType:iterator,
    isChangeValue:false,
    parameter:''
  },
]

export default arrayList
