import { num, noReturn, str } from './type.js'

const dateList = [
  {
    name: 'Date.UTC()',
    mdnLink: 'https://developer.mozilla.org/zh-CN/docs/Web/JavaScript/Reference/Global_Objects/Date/UTC',
    explanation:
      '接受與建構子相同長度的參數，將參數視為通用時間（UTC）來計算回傳由 1970-01-01 00:00:00 UTC 所經過的毫秒數。',
    returnType: num,
    isChangeValue: false,
    parameter: 'year, month, day, hour, minute, second, millisecond',
  },
  {
    name: 'Date.now()',
    mdnLink: 'https://developer.mozilla.org/zh-CN/docs/Web/JavaScript/Reference/Global_Objects/Date/now',
    explanation: '回傳自 1970/01/01 00:00:00 UTC 起經過的毫秒數。',
    returnType: num,
    isChangeValue: false,
    parameter: '',
  },
  {
    name: 'Date.parse()',
    mdnLink: 'https://developer.mozilla.org/zh-CN/docs/Web/JavaScript/Reference/Global_Objects/Date/parse',
    explanation:
      '解析一個表示某個日期的字符串，並返回從1970-1-1 00:00:00 UTC 到該日期物件（該日期物件的UTC時間）的毫秒數，如果該字符串無法識別，或者一些情況下，包含了不合法的日期數值（如：2015-02-31），則返回值為NaN。',
    returnType: num,
    isChangeValue: false,
    parameter: 'dateString',
  },
  {
    name: 'Date.prototype.getDate()',
    mdnLink: 'https://developer.mozilla.org/zh-CN/docs/Web/JavaScript/Reference/Global_Objects/Date/getDate',
    explanation: '根據本地時間，返回一個指定的日期物件為一個月中的哪一日（從1~31）。',
    returnType: num,
    isChangeValue: false,
    parameter: '',
  },
  {
    name: 'Date.prototype.getDay()',
    mdnLink: 'https://developer.mozilla.org/zh-CN/docs/Web/JavaScript/Reference/Global_Objects/Date/getDay',
    explanation: '根據本地時間，返回一個具體日期中一周的第幾天，0 表示星期天。對於某個月中的第幾天',
    returnType: num,
    isChangeValue: false,
    parameter: '',
  },
  {
    name: 'Date.prototype.getFullYear()',
    mdnLink: 'https://developer.mozilla.org/zh-CN/docs/Web/JavaScript/Reference/Global_Objects/Date/getFullYear',
    explanation: '根據本地時間返回指定日期的年份。',
    returnType: num,
    isChangeValue: false,
    parameter: '',
  },
  {
    name: 'Date.prototype.getHours()',
    mdnLink: 'https://developer.mozilla.org/zh-CN/docs/Web/JavaScript/Reference/Global_Objects/Date/getHours',
    explanation: '根據本地時間，返回一個指定的日期物件的小時。',
    returnType: num,
    isChangeValue: false,
    parameter: '',
  },
  {
    name: 'Date.prototype.getMilliseconds()',
    mdnLink: 'https://developer.mozilla.org/zh-CN/docs/Web/JavaScript/Reference/Global_Objects/Date/getMilliseconds',
    explanation: '根據本地時間，返回一個指定的日期物件的毫秒數。',
    returnType: num,
    isChangeValue: false,
    parameter: '',
  },
  {
    name: 'Date.prototype.getMinutes()',
    mdnLink: 'https://developer.mozilla.org/zh-CN/docs/Web/JavaScript/Reference/Global_Objects/Date/getMinutes',
    explanation: '根據本地時間，返回一個指定的日期物件的分鐘數。',
    returnType: num,
    isChangeValue: false,
    parameter: '',
  },
  {
    name: 'Date.prototype.getMonth()',
    mdnLink: 'https://developer.mozilla.org/zh-CN/docs/Web/JavaScript/Reference/Global_Objects/Date/getMonth',
    explanation: '根據本地時間，返回一個指定的日期物件的月份，為基於0的值（0表示一年中的第一月）。',
    returnType: num,
    isChangeValue: false,
    parameter: '',
  },
  {
    name: 'Date.prototype.getSeconds()',
    mdnLink: 'https://developer.mozilla.org/zh-CN/docs/Web/JavaScript/Reference/Global_Objects/Date/getSeconds',
    explanation: '根據本地時間，返回一個指定的日期物件的秒數。',
    returnType: num,
    isChangeValue: false,
    parameter: '',
  },
  {
    name: 'Date.prototype.getTime()',
    mdnLink: 'https://developer.mozilla.org/zh-CN/docs/Web/JavaScript/Reference/Global_Objects/Date/getTime',
    explanation: '返回一個時間的格林威治時間數值。',
    returnType: num,
    isChangeValue: false,
    parameter: '',
  },
  {
    name: 'Date.prototype.getTimezoneOffset()',
    mdnLink: 'https://developer.mozilla.org/zh-CN/docs/Web/JavaScript/Reference/Global_Objects/Date/getTimezoneOffset',
    explanation: '返回協調世界時間（UTC）相對於當前時區的時間差值，單位為分鐘。',
    returnType: num,
    isChangeValue: false,
    parameter: '',
  },
  {
    name: 'Date.prototype.getUTCDate()',
    mdnLink: 'https://developer.mozilla.org/zh-CN/docs/Web/JavaScript/Reference/Global_Objects/Date/getUTCDate',
    explanation: '以世界時為標準，返回一個指定的日期物件為一個月中的第幾天',
    returnType: num,
    isChangeValue: false,
    parameter: '',
  },
  {
    name: 'Date.prototype.getUTCDay()',
    mdnLink: 'https://developer.mozilla.org/zh-CN/docs/Web/JavaScript/Reference/Global_Objects/Date/getUTCDay',
    explanation: '以世界時為標準，返回一個指定的日期物件為一星期中的第幾天，其中 0 代表星期天。',
    returnType: num,
    isChangeValue: false,
    parameter: '',
  },
  {
    name: 'Date.prototype.getUTCFullYear()',
    mdnLink: 'https://developer.mozilla.org/zh-CN/docs/Web/JavaScript/Reference/Global_Objects/Date/getUTCFullYear',
    explanation: '以世界時為標準，返回一個指定的日期物件的年份。',
    returnType: num,
    isChangeValue: false,
    parameter: '',
  },
  {
    name: 'Date.prototype.getUTCHours()',
    mdnLink: 'https://developer.mozilla.org/zh-CN/docs/Web/JavaScript/Reference/Global_Objects/Date/getUTCHours',
    explanation: '以世界時為標準，返回一個指定的日期物件的小時數。',
    returnType: num,
    isChangeValue: false,
    parameter: '',
  },
  {
    name: 'Date.prototype.getUTCMilliseconds()',
    mdnLink: 'https://developer.mozilla.org/zh-CN/docs/Web/JavaScript/Reference/Global_Objects/Date/getUTCMilliseconds',
    explanation: '以世界時為標準，返回一個指定的日期物件的毫秒數。',
    returnType: num,
    isChangeValue: false,
    parameter: '',
  },
  {
    name: 'Date.prototype.getUTCMinutes()',
    mdnLink: 'https://developer.mozilla.org/zh-CN/docs/Web/JavaScript/Reference/Global_Objects/Date/getUTCMinutes',
    explanation: '以世界時為標準，返回一個指定的日期物件的分鐘數。',
    returnType: num,
    isChangeValue: false,
    parameter: '',
  },
  {
    name: 'Date.prototype.getUTCMonth()',
    mdnLink: 'https://developer.mozilla.org/zh-CN/docs/Web/JavaScript/Reference/Global_Objects/Date/getUTCMonth',
    explanation: '以世界時為標準，返回一個指定的日期物件的月份，它是從 0 開始計數的（0 代表一年的第一個月）。',
    returnType: num,
    isChangeValue: false,
    parameter: '',
  },
  {
    name: 'Date.prototype.getUTCSeconds()',
    mdnLink: 'https://developer.mozilla.org/zh-CN/docs/Web/JavaScript/Reference/Global_Objects/Date/getUTCSeconds',
    explanation: '以世界時為標準，返回一個指定的日期物件的秒數。',
    returnType: num,
    isChangeValue: false,
    parameter: '',
  },
  {
    name: 'Date.prototype.setDate()',
    mdnLink: 'https://developer.mozilla.org/zh-CN/docs/Web/JavaScript/Reference/Global_Objects/Date/setDate',
    explanation: '根據本地時間來指定一個日期物件的天數。',
    returnType: noReturn,
    isChangeValue: false,
    parameter: 'dayValue',
  },
  {
    name: 'Date.prototype.setFullYear()',
    mdnLink: 'https://developer.mozilla.org/zh-CN/docs/Web/JavaScript/Reference/Global_Objects/Date/setFullYear',
    explanation: '根據本地時間為一個日期物件設置年份。',
    returnType: noReturn,
    isChangeValue: false,
    parameter: 'yearValue, *monthValue, *dayValue',
  },
  {
    name: 'Date.prototype.setHours()',
    mdnLink: 'https://developer.mozilla.org/zh-CN/docs/Web/JavaScript/Reference/Global_Objects/Date/setHours',
    explanation:
      '根據本地時間為一個日期物件設置小時數，返回從1970-01-01 00:00:00 UTC 到更新後的日期物件實例所表示時間的毫秒數。',
    returnType: noReturn,
    isChangeValue: false,
    parameter: 'hoursValue, *minutesValue, *secondsValue, *msValue',
  },
  {
    name: 'Date.prototype.setMilliseconds()',
    mdnLink: 'https://developer.mozilla.org/zh-CN/docs/Web/JavaScript/Reference/Global_Objects/Date/setMilliseconds',
    explanation: '根據本地時間設置一個日期物件的豪秒數。',
    returnType: noReturn,
    isChangeValue: false,
    parameter: 'millisecondsValue',
  },
  {
    name: 'Date.prototype.setMinutes()',
    mdnLink: 'https://developer.mozilla.org/zh-CN/docs/Web/JavaScript/Reference/Global_Objects/Date/setMinutes',
    explanation: '根據本地時間為一個日期物件設置分鐘數。',
    returnType: noReturn,
    isChangeValue: false,
    parameter: 'minutesValue, *secondsValue, *msValue',
  },
  {
    name: 'Date.prototype.setMonth()',
    mdnLink: 'https://developer.mozilla.org/zh-CN/docs/Web/JavaScript/Reference/Global_Objects/Date/setMonth',
    explanation: '根據本地時間為一個設置年份的日期物件設置月份。',
    returnType: noReturn,
    isChangeValue: false,
    parameter: 'monthValue, *dayValue',
  },
  {
    name: 'Date.prototype.setSeconds()',
    mdnLink: 'https://developer.mozilla.org/zh-CN/docs/Web/JavaScript/Reference/Global_Objects/Date/setSeconds',
    explanation: '根據本地時間設置一個日期物件的秒數。',
    returnType: noReturn,
    isChangeValue: false,
    parameter: 'secondsValue, *msValue',
  },
  {
    name: 'Date.prototype.setTime()',
    mdnLink: 'https://developer.mozilla.org/zh-CN/docs/Web/JavaScript/Reference/Global_Objects/Date/setTime',
    explanation: '以一個表示從1970-1-1 00:00:00 UTC計時的毫秒數為來為 Date 物件設置時間。',
    returnType: noReturn,
    isChangeValue: false,
    parameter: 'timeValue',
  },
  {
    name: 'Date.prototype.setUTCDate()',
    mdnLink: 'https://developer.mozilla.org/zh-CN/docs/Web/JavaScript/Reference/Global_Objects/Date/setUTCDate',
    explanation: '根據全球時間設置特定date物件的日期。',
    returnType: noReturn,
    isChangeValue: false,
    parameter: 'dayValue',
  },
  {
    name: 'Date.prototype.setUTCFullYear()',
    mdnLink: 'https://developer.mozilla.org/zh-CN/docs/Web/JavaScript/Reference/Global_Objects/Date/setUTCFullYear',
    explanation: '根據世界標準時間為一個具體日期設置年份。',
    returnType: noReturn,
    isChangeValue: false,
    parameter: 'yearValue, *monthValue, *dayValue',
  },
  {
    name: 'Date.prototype.setUTCHours()',
    mdnLink: 'https://developer.mozilla.org/zh-CN/docs/Web/JavaScript/Reference/Global_Objects/Date/setUTCHours',
    explanation:
      '根據世界標準時間為一個日期物件設置小時數，返回從1970-01-01 00:00:00 UTC 到更新後的日期物件實例所表示時間的毫秒數。',
    returnType: noReturn,
    isChangeValue: false,
    parameter: 'hoursValue, *minutesValue, *secondsValue, *msValue',
  },
  {
    name: 'Date.prototype.setUTCMilliseconds()',
    mdnLink: 'https://developer.mozilla.org/zh-CN/docs/Web/JavaScript/Reference/Global_Objects/Date/setUTCMilliseconds',
    explanation: '根據世界時間來設置指定時間的毫秒數。',
    returnType: noReturn,
    isChangeValue: false,
    parameter: 'millisecondsValue',
  },
  {
    name: 'Date.prototype.setUTCMinutes()',
    mdnLink: 'https://developer.mozilla.org/zh-CN/docs/Web/JavaScript/Reference/Global_Objects/Date/setUTCMinutes',
    explanation: '根據世界協調時間（UTC）來設置指定日期的分鐘數。',
    returnType: noReturn,
    isChangeValue: false,
    parameter: 'minutesValue, *secondsValue, *msValue',
  },
  {
    name: 'Date.prototype.setUTCMonth()',
    mdnLink: 'https://developer.mozilla.org/zh-CN/docs/Web/JavaScript/Reference/Global_Objects/Date/setUTCMonth',
    explanation: '根據世界時間來設置一個指定的月份',
    returnType: noReturn,
    isChangeValue: false,
    parameter: 'monthValue, *dayValue',
  },
  {
    name: 'Date.prototype.setUTCSeconds()',
    mdnLink: 'https://developer.mozilla.org/zh-CN/docs/Web/JavaScript/Reference/Global_Objects/Date/setUTCSeconds',
    explanation: '依據世界通用時間的特定日期設置秒數。',
    returnType: noReturn,
    isChangeValue: false,
    parameter: 'secondsValue, *msValue',
  },
  {
    name: 'Date.prototype.toDateString()',
    mdnLink: 'https://developer.mozilla.org/zh-CN/docs/Web/JavaScript/Reference/Global_Objects/Date/toDateString',
    explanation: '以美式英語和人類易讀的形式返回一個日期對像日期部分的字符串。',
    returnType: str,
    isChangeValue: false,
    parameter: '',
  },
  {
    name: 'Date.prototype.toISOString()',
    mdnLink: 'https://developer.mozilla.org/zh-CN/docs/Web/JavaScript/Reference/Global_Objects/Date/toISOString',
    explanation:
      '返回一個 ISO（ISO 8601 Extended Format）格式的字符串： YYYY-MM-DDTHH:mm:ss.sssZ。時區總是UTC（世界時間），加一個後綴“Z”標識。',
    returnType: str,
    isChangeValue: false,
    parameter: '',
  },
  {
    name: 'Date.prototype.toJSON()',
    mdnLink: 'https://developer.mozilla.org/zh-CN/docs/Web/JavaScript/Reference/Global_Objects/Date/toJSON',
    explanation: '返回Date物件的字符串形式。',
    returnType: str,
    isChangeValue: false,
    parameter: '',
  },
  {
    name: 'Date.prototype.toLocaleDateString()',
    mdnLink: 'https://developer.mozilla.org/zh-CN/docs/Web/JavaScript/Reference/Global_Objects/Date/toLocaleDateString',
    explanation:
      '返回該日期對像日期部分的字符串，該字符串格式因不同語言而不同。新增的參數 locales 和 options 使程序能夠指定使用哪種語言格式化規則，允許定制該方法的表現（behavior）。',
    returnType: str,
    isChangeValue: false,
    parameter: 'locales, options',
  },
  {
    name: 'Date.prototype.toLocaleString()',
    mdnLink: 'https://developer.mozilla.org/zh-CN/docs/Web/JavaScript/Reference/Global_Objects/Date/toLocaleString',
    explanation:
      '返回該日期物件的字符串，該字符串格式因不同語言而不同。新增的參數 locales 和 options 使程序能夠指定使用哪種語言格式化規則，允許定制該方法的表現（behavior）。',
    returnType: str,
    isChangeValue: false,
    parameter: 'locales, options',
  },
  {
    name: 'Date.prototype.toLocaleTimeString()',
    mdnLink: 'https://developer.mozilla.org/zh-CN/docs/Web/JavaScript/Reference/Global_Objects/Date/toLocaleTimeString',
    explanation:
      '返回該日期物件時間部分的字符串，該字符串格式因不同語言而不同。新增的參數 locales 和 options 使程序能夠指定使用哪種語言格式化規則，允許定制該方法的表現（behavior）。',
    returnType: str,
    isChangeValue: false,
    parameter: 'locales, options',
  },
  {
    name: 'Date.prototype.toString()',
    mdnLink: 'https://developer.mozilla.org/zh-CN/docs/Web/JavaScript/Reference/Global_Objects/Date/toString',
    explanation: '返回一個字符串，表示該Date物件。',
    returnType: str,
    isChangeValue: false,
    parameter: '',
  },
  {
    name: 'Date.prototype.toTimeString()',
    mdnLink: 'https://developer.mozilla.org/zh-CN/docs/Web/JavaScript/Reference/Global_Objects/Date/toTimeString',
    explanation: '以人類易讀形式返回一個日期物件時間部分的字符串，該字符串以美式英語格式化。',
    returnType: str,
    isChangeValue: false,
    parameter: '',
  },
  {
    name: 'Date.prototype.toUTCString()',
    mdnLink: 'https://developer.mozilla.org/zh-CN/docs/Web/JavaScript/Reference/Global_Objects/Date/toUTCString',
    explanation: '把一個日期轉換為一個字符串，使用UTC時區。',
    returnType: str,
    isChangeValue: false,
    parameter: '',
  },
  {
    name: 'Date.prototype.valueOf()',
    mdnLink: 'https://developer.mozilla.org/zh-CN/docs/Web/JavaScript/Reference/Global_Objects/Date/valueOf',
    explanation: '返回一個 Date 物件的原始值。',
    returnType: num,
    isChangeValue: false,
    parameter: '',
  },
]

export default dateList
