import { num } from './type.js'

const mathList = [
  {
    name: 'Math.abs()',
    mdnLink: 'https://developer.mozilla.org/zh-TW/docs/Web/JavaScript/Reference/Global_Objects/Math/abs',
    explanation: '回傳一個數字的絕對值',
    returnType: num,
    isChangeValue: false,
    parameter: 'x',
  },
  {
    name: 'Math.acos()',
    mdnLink: 'https://developer.mozilla.org/zh-TW/docs/Web/JavaScript/Reference/Global_Objects/Math/aocs',
    explanation: '返回一個數的反餘弦值（單位為弧度）',
    returnType: num,
    isChangeValue: false,
    parameter: 'x',
  },
  {
    name: 'Math.acosh()',
    mdnLink: 'https://developer.mozilla.org/zh-TW/docs/Web/JavaScript/Reference/Global_Objects/Math/acosh',
    explanation: '返回一個數字的反雙曲餘弦值',
    returnType: num,
    isChangeValue: false,
    parameter: 'x',
  },
  {
    name: 'Math.asin()',
    mdnLink: 'https://developer.mozilla.org/zh-TW/docs/Web/JavaScript/Reference/Global_Objects/Math/asin',
    explanation: '返回一個數的反正弦值（單位為弧度）',
    returnType: num,
    isChangeValue: false,
    parameter: 'x',
  },
  {
    name: 'Math.asinh()',
    mdnLink: 'https://developer.mozilla.org/zh-TW/docs/Web/JavaScript/Reference/Global_Objects/Math/asinh',
    explanation: '返回一個數字的反雙曲正弦值',
    returnType: num,
    isChangeValue: false,
    parameter: 'x',
  },
  {
    name: 'Math.atan()',
    mdnLink: 'https://developer.mozilla.org/zh-TW/docs/Web/JavaScript/Reference/Global_Objects/Math/atan',
    explanation: '返回一個數值的反正切（單位為弧度）',
    returnType: num,
    isChangeValue: false,
    parameter: 'x',
  },
  {
    name: 'Math.atan2()',
    mdnLink: 'https://developer.mozilla.org/zh-TW/docs/Web/JavaScript/Reference/Global_Objects/Math/atan2',
    explanation: '返回從原點(0,0)到(x,y)點的線段與x軸正方向之間的平面角度(弧度值)，也就是Math.atan2(y,x)',
    returnType: num,
    isChangeValue: false,
    parameter: 'y, x',
  },
  {
    name: 'Math.atanh()',
    mdnLink: 'https://developer.mozilla.org/zh-TW/docs/Web/JavaScript/Reference/Global_Objects/Math/atanh',
    explanation: '返回一個數值反雙曲正切值',
    returnType: num,
    isChangeValue: false,
    parameter: 'x',
  },
  {
    name: 'Math.cbrt()',
    mdnLink: 'https://developer.mozilla.org/zh-TW/docs/Web/JavaScript/Reference/Global_Objects/Math/cbrt',
    explanation: '返回任意數字的立方根',
    returnType: num,
    isChangeValue: false,
    parameter: 'x',
  },
  {
    name: 'Math.ceil()',
    mdnLink: 'https://developer.mozilla.org/zh-TW/docs/Web/JavaScript/Reference/Global_Objects/Math/ceil',
    explanation: '返回大於或等於一個给定數字的最小整數',
    returnType: num,
    isChangeValue: false,
    parameter: 'x',
  },
  {
    name: 'Math.clz32()',
    mdnLink: 'https://developer.mozilla.org/zh-TW/docs/Web/JavaScript/Reference/Global_Objects/Math/clz32',
    explanation: '返回一個數字在轉換成 32 無符號整形數字的二進制形式後, 開頭為 0 的個數',
    returnType: num,
    isChangeValue: false,
    parameter: 'x',
  },
  {
    name: 'Math.cos()',
    mdnLink: 'https://developer.mozilla.org/zh-TW/docs/Web/JavaScript/Reference/Global_Objects/Math/cos',
    explanation: '返回一個數值的餘弦值',
    returnType: num,
    isChangeValue: false,
    parameter: 'x',
  },
  {
    name: 'Math.cosh()',
    mdnLink: 'https://developer.mozilla.org/zh-TW/docs/Web/JavaScript/Reference/Global_Objects/Math/cosh',
    explanation: '返回一個數值的雙曲餘弦函數',
    returnType: num,
    isChangeValue: false,
    parameter: 'x',
  },
  {
    name: 'Math.exp()',
    mdnLink: 'https://developer.mozilla.org/zh-TW/docs/Web/JavaScript/Reference/Global_Objects/Math/exp',
    explanation: "返回 e^x，x 表示参數，e 是歐拉常數（Euler's constant），自然對數的底數。",
    returnType: num,
    isChangeValue: false,
    parameter: 'x',
  },
  {
    name: 'Math.expm1()',
    mdnLink: 'https://developer.mozilla.org/zh-TW/docs/Web/JavaScript/Reference/Global_Objects/Math/expm1',
    explanation: '返回 e^x - 1, 其中 x 是該函數的参數, e 是自然對數的底數 2.718281828459045',
    returnType: num,
    isChangeValue: false,
    parameter: 'x',
  },
  {
    name: 'Math.floor()',
    mdnLink: 'https://developer.mozilla.org/zh-TW/docs/Web/JavaScript/Reference/Global_Objects/Math/floor',
    explanation: '返回小於或等於一個给定數字的最大整數。',
    returnType: num,
    isChangeValue: false,
    parameter: 'x',
  },
  {
    name: 'Math.fround()',
    mdnLink: 'https://developer.mozilla.org/zh-TW/docs/Web/JavaScript/Reference/Global_Objects/Math/fround',
    explanation: '將任意的數字轉换為離它最近的單精度浮點數形式的數字。',
    returnType: num,
    isChangeValue: false,
    parameter: 'x',
  },
  {
    name: 'Math.hypot()',
    mdnLink: 'https://developer.mozilla.org/zh-TW/docs/Web/JavaScript/Reference/Global_Objects/Math/hypot',
    explanation: '返回它的所有参數的平方和的平方根',
    returnType: num,
    isChangeValue: false,
    parameter: 'val1, val2,...valN',
  },
  {
    name: 'Math.imul()',
    mdnLink: 'https://developer.mozilla.org/zh-TW/docs/Web/JavaScript/Reference/Global_Objects/Math/imul',
    explanation: '將兩個参數分别轉换為 32 位整數，相乘後返回 32 位结果，類似 C 語言的 32 位整數相乘。',
    returnType: num,
    isChangeValue: false,
    parameter: 'a, b',
  },
  {
    name: 'Math.log()',
    mdnLink: 'https://developer.mozilla.org/zh-TW/docs/Web/JavaScript/Reference/Global_Objects/Math/log',
    explanation: '返回一個數的自然對數',
    returnType: num,
    isChangeValue: false,
    parameter: 'x',
  },
  {
    name: 'Math.log10()',
    mdnLink: 'https://developer.mozilla.org/zh-TW/docs/Web/JavaScript/Reference/Global_Objects/Math/log10',
    explanation: '返回一個數字以 10 為底的對數',
    returnType: num,
    isChangeValue: false,
    parameter: 'x',
  },
  {
    name: 'Math.log1p()',
    mdnLink: 'https://developer.mozilla.org/zh-TW/docs/Web/JavaScript/Reference/Global_Objects/Math/log1p',
    explanation: '返回一個數字加1後的自然對數 (底為 E), 即log(x+1)',
    returnType: num,
    isChangeValue: false,
    parameter: 'x',
  },
  {
    name: 'Math.log2()',
    mdnLink: 'https://developer.mozilla.org/zh-TW/docs/Web/JavaScript/Reference/Global_Objects/Math/log2',
    explanation: '返回一個數字以 2 為底的對數.',
    returnType: num,
    isChangeValue: false,
    parameter: 'x',
  },
  {
    name: 'Math.max()',
    mdnLink: 'https://developer.mozilla.org/zh-TW/docs/Web/JavaScript/Reference/Global_Objects/Math/max',
    explanation: '返回一组數中的最大值',
    returnType: num,
    isChangeValue: false,
    parameter: 'val1, val2,...valN',
  },
  {
    name: 'Math.min()',
    mdnLink: 'https://developer.mozilla.org/zh-TW/docs/Web/JavaScript/Reference/Global_Objects/Math/min',
    explanation: '零個或更多個數值的最小值',
    returnType: num,
    isChangeValue: false,
    parameter: 'val1, val2,...valN',
  },
  {
    name: 'Math.pow()',
    mdnLink: 'https://developer.mozilla.org/zh-TW/docs/Web/JavaScript/Reference/Global_Objects/Math/pow',
    explanation: '返回基數（base）的指數（exponent）次冪，即 base^exponent',
    returnType: num,
    isChangeValue: false,
    parameter: 'base, exponent',
  },
  {
    name: 'Math.random()',
    mdnLink: 'https://developer.mozilla.org/zh-TW/docs/Web/JavaScript/Reference/Global_Objects/Math/random',
    explanation: '返回一個浮點，偽隨機數在範圍從0到小於1，也就是說，從0（包括0）往上，但是不包括1（排除1），然後您可以縮放到所需的範圍。實現將初始種子選擇到隨機數生成算法; 它不能被用戶選擇或重置。',
    returnType: num,
    isChangeValue: false,
    parameter: '',
  },
  {
    name: 'Math.round()',
    mdnLink: 'https://developer.mozilla.org/zh-TW/docs/Web/JavaScript/Reference/Global_Objects/Math/round',
    explanation: '返回一個數字四捨五入後最接近的整數',
    returnType: num,
    isChangeValue: false,
    parameter: 'x',
  },
  {
    name: 'Math.sign()',
    mdnLink: 'https://developer.mozilla.org/zh-TW/docs/Web/JavaScript/Reference/Global_Objects/Math/sign',
    explanation: '返回一個數字的符號, 指示數字是正數，負數還是零',
    returnType: num,
    isChangeValue: false,
    parameter: 'x',
  },
  {
    name: 'Math.sin()',
    mdnLink: 'https://developer.mozilla.org/zh-TW/docs/Web/JavaScript/Reference/Global_Objects/Math/sin',
    explanation: '返回一個數值的正弦值',
    returnType: num,
    isChangeValue: false,
    parameter: 'x',
  },
  {
    name: 'Math.sinh()',
    mdnLink: 'https://developer.mozilla.org/zh-TW/docs/Web/JavaScript/Reference/Global_Objects/Math/sinh',
    explanation: '返回一個數字(單位為角度)的雙曲正弦值',
    returnType: num,
    isChangeValue: false,
    parameter: 'x',
  },
  {
    name: 'Math.sqrt()',
    mdnLink: 'https://developer.mozilla.org/zh-TW/docs/Web/JavaScript/Reference/Global_Objects/Math/sqrt',
    explanation: '返回一個數的平方根',
    returnType: num,
    isChangeValue: false,
    parameter: 'x',
  },
  {
    name: 'Math.tan()',
    mdnLink: 'https://developer.mozilla.org/zh-TW/docs/Web/JavaScript/Reference/Global_Objects/Math/tan',
    explanation: '返回一個數值的正切值',
    returnType: num,
    isChangeValue: false,
    parameter: 'x',
  },
  {
    name: 'Math.tanh()',
    mdnLink: 'https://developer.mozilla.org/zh-TW/docs/Web/JavaScript/Reference/Global_Objects/Math/tanh',
    explanation: '將會返回一個數的雙曲正切函數值',
    returnType: num,
    isChangeValue: false,
    parameter: 'x',
  },
  {
    name: 'Math.trunc()',
    mdnLink: 'https://developer.mozilla.org/zh-TW/docs/Web/JavaScript/Reference/Global_Objects/Math/trunc',
    explanation: '會將數字的小數部分去掉，只保留整數部分。',
    returnType: num,
    isChangeValue: false,
    parameter: 'value',
  },
]

export default mathList
